-- Create coupons table if it doesn't exist
CREATE TABLE IF NOT EXISTS COUPONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    MIN_ORDER_AMOUNT DECIMAL(10,2),
    MAX_DISCOUNT_AMOUNT DECIMAL(10,2),
    USAGE_LIMIT INT NOT NULL,
    USED_COUNT INT NOT NULL DEFAULT 0,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_UNTIL TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

-- Insert sample coupon data if table is empty
INSERT INTO COUPONS (CODE, DESCRIPTION, DISCOUNT_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_DISCOUNT_AMOUNT, USAGE_LIMIT, USED_COUNT, VALID_FROM, VALID_UNTIL, ACTIVE, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 
        'WELCOME10' as CODE,
        'Welcome offer - 10% off on your first purchase' as DESCRIPTION,
        'PERCENTAGE' as DISCOUNT_TYPE,
        10.00 as DISCOUNT_VALUE,
        1000.00 as MIN_ORDER_AMOUNT,
        500.00 as MAX_DISCOUNT_AMOUNT,
        100 as USAGE_LIMIT,
        0 as USED_COUNT,
        CURRENT_TIMESTAMP() - INTERVAL '1' DAY as VALID_FROM,
        CURRENT_TIMESTAMP() + INTERVAL '3' MONTH as VALID_UNTIL,
        TRUE as ACTIVE,
        CURRENT_TIMESTAMP() as CREATED_AT,
        CURRENT_TIMESTAMP() as UPDATED_AT
) WHERE NOT EXISTS (SELECT 1 FROM COUPONS);
