-- Sample Products for Perfume Shop Chatbot (imported after schema creation)
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (1, 'Gucci Bloom', 'Gucci', 'A fresh floral composition with gardenia, tuberose, and jasmine. Elegant and refined, perfect for daytime wear.', 3800, 38, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1595777712802-372adc3dd05e?w=500', true, true, 4.5, 234, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (2, 'Dior Jadore', 'Dior', 'Luxurious floral fragrance with notes of jasmine, rose, and orange blossom. A symbol of absolute femininity and elegance.', 4200, 52, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1562181286-d3fee7d55364?w=500', true, true, 4.7, 312, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (3, 'Chanel No. 5', 'Chanel', 'The iconic timeless classic. A floral bouquet with top notes of neroli and ylang-ylang. Sophisticated and elegant for the modern woman.', 4500, 45, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1596178065887-cf38d2e3e02f?w=500', true, true, 4.8, 445, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (4, 'Dior Sauvage', 'Dior', 'Fresh and spicy fragrance with ambroxan, pepper, and ambrette seed. The most versatile mens fragrance ever.', 2500, 67, 'Men', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500', true, true, 4.9, 567, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (5, 'Bleu de Chanel', 'Chanel', 'A sophisticated fragrance with notes of citrus, ginger, and cedar. Modern, fresh, and masculine.', 2800, 58, 'Men', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1613467489881-a59c0cda0b2b?w=500', true, true, 4.7, 389, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (6, 'Prada L''Homme', 'Prada', 'Refined woody fragrance with iris, ambroxan, and incense. Modern and elegant.', 4500, 44, 'Men', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1559056199-641a0ac8b8d5?w=500', true, true, 4.6, 278, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (7, 'Giorgio Armani Code', 'Giorgio Armani', 'Sophisticated and warm fragrance with iris, ambroxan, and leather. The ultimate masculine scent.', 5200, 48, 'Men', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1595836374141-a96df00e5f30?w=500', true, true, 4.5, 301, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (8, 'Tom Ford Black Orchid', 'Tom Ford', 'A luxurious and sensual fragrance blending black orchid with dark chocolate and rum. Deep and mysterious.', 6500, 28, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', true, true, 4.6, 267, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (9, 'Lancôme Trésor', 'Lancôme', 'Luxurious oriental fragrance with vanilla, amber, and flowers. Sensual and warm.', 7200, 47, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1597318372441-0a2c8cf4f4bb?w=500', true, true, 4.4, 189, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (10, 'Marc Jacobs Daisy Love', 'Marc Jacobs', 'Fresh and flirty fragrance with wildflower, white raspberry, and vanilla.', 2200, 72, 'Unisex', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1548695207-9b3f53c4c82f?w=500', true, true, 4.3, 156, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (11, 'Jo Malone Cologne', 'Jo Malone', 'Light and refreshing fragrance. Versatile and perfect for layering.', 2600, 88, 'Unisex', 'Eau de Cologne', 100, 'https://images.unsplash.com/photo-1570538108519-280658a16dda?w=500', true, true, 4.5, 223, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (12, 'Burberry Brit Sheer', 'Burberry', 'Fruity fragrance with yuzu, peony, and subtle musk. Fresh and summery.', 2200, 54, 'Women', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1591186995819-4c5150e5e44d?w=500', true, true, 4.2, 134, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (13, 'Marc Jacobs Decadence', 'Marc Jacobs', 'Rich fruity fragrance with peach, wildflower, and almond. Luxurious and sensual.', 2600, 46, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500', true, true, 4.4, 198, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (14, 'Lancôme La Vie Est Belle', 'Lancôme', 'Best-selling fragrance with praline, iris, and patchouli. Sweet and irresistible.', 2000, 95, 'Women', 'Eau de Parfum', 75, 'https://images.unsplash.com/photo-1569505254788-205b4f368f5f?w=500', true, true, 4.6, 412, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (15, 'Hugo Boss Bottled', 'Hugo Boss', 'Best-selling mens fragrance with apple, cinnamon, and leather. Perfect daily scent.', 1800, 81, 'Men', 'Eau de Toilette', 100, 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500', true, true, 4.4, 356, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (16, 'Creed Aventus', 'Creed', 'Legendary fragrance with pineapple, blackcurrant, and oakmoss. Bold, commanding, and unforgettable.', 8500, 15, 'Men', 'Eau de Parfum', 120, 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=500', true, true, 4.9, 423, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO products (id, name, brand, description, price, stock, category, type, volume, image_url, featured, active, rating, review_count, created_at, updated_at) VALUES (17, 'Flowerbomb Viktor & Rolf', 'Viktor & Rolf', 'Explosive floral fragrance with sambac jasmine and centifolia rose. Intoxicating.', 3500, 29, 'Women', 'Eau de Parfum', 100, 'https://images.unsplash.com/photo-1577875729629-ed5fdc1d3dc3?w=500', true, true, 4.7, 298, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
