CREATE TABLE IF NOT EXISTS COUPONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE DECIMAL(10,2) NOT NULL,
    MIN_ORDER_AMOUNT DECIMAL(10,2),
    MAX_DISCOUNT_AMOUNT DECIMAL(10,2),
    USAGE_LIMIT INT NOT NULL,
    USED_COUNT INT NOT NULL DEFAULT 0,
    VALID_FROM TIMESTAMP NOT NULL,
    VALID_UNTIL TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);
