package com.perfume.shop.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO for Razorpay Order creation
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class RazorpayOrderResponse {
    
    private String razorpayOrderId; // Razorpay Order ID to be passed to frontend
    
    private String razorpayKeyId; // Razorpay Public Key for frontend
    
    private Long amount; // Amount in smallest currency unit
    
    private String currency;
    
    private Long orderId; // Our Order ID
    
    private String orderNumber; // Our Order Number
    
    private String customerEmail;
    
    private String customerName;
    
    private String customerPhone;
    
    /**
     * Create a copy with specific fields overridden
     */
    public static class RazorpayOrderResponseBuilder {
        // This is auto-generated by Lombok @Builder
    }
}
